// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paymentchannels.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_CHANNEL_OPEN             Message_MessageType = 0
	Message_CHANNEL_ACCEPT           Message_MessageType = 1
	Message_INITIAL_COMMIT           Message_MessageType = 2
	Message_INITIAL_COMMIT_SIGNATURE Message_MessageType = 3
	Message_CHANNEL_UPDATE_PROPOSAL  Message_MessageType = 4
	Message_UPDATE_PROPOSAL_ACCEPT   Message_MessageType = 5
	Message_FINALIZE_UPDATE          Message_MessageType = 6
	Message_SHUTDOWN                 Message_MessageType = 7
	Message_ERROR                    Message_MessageType = 8
)

var Message_MessageType_name = map[int32]string{
	0: "CHANNEL_OPEN",
	1: "CHANNEL_ACCEPT",
	2: "INITIAL_COMMIT",
	3: "INITIAL_COMMIT_SIGNATURE",
	4: "CHANNEL_UPDATE_PROPOSAL",
	5: "UPDATE_PROPOSAL_ACCEPT",
	6: "FINALIZE_UPDATE",
	7: "SHUTDOWN",
	8: "ERROR",
}

var Message_MessageType_value = map[string]int32{
	"CHANNEL_OPEN":             0,
	"CHANNEL_ACCEPT":           1,
	"INITIAL_COMMIT":           2,
	"INITIAL_COMMIT_SIGNATURE": 3,
	"CHANNEL_UPDATE_PROPOSAL":  4,
	"UPDATE_PROPOSAL_ACCEPT":   5,
	"FINALIZE_UPDATE":          6,
	"SHUTDOWN":                 7,
	"ERROR":                    8,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{0, 0}
}

type Message struct {
	MessageType          Message_MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=Message_MessageType" json:"messageType,omitempty"`
	Payload              *any.Any            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageType() Message_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Message_CHANNEL_OPEN
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ChannelOpen struct {
	AddressID            []byte   `protobuf:"bytes,1,opt,name=addressID,proto3" json:"addressID,omitempty"`
	ChannelPubkey        []byte   `protobuf:"bytes,2,opt,name=channelPubkey,proto3" json:"channelPubkey,omitempty"`
	FeePerByte           uint32   `protobuf:"varint,3,opt,name=feePerByte,proto3" json:"feePerByte,omitempty"`
	DustLimit            uint64   `protobuf:"varint,4,opt,name=dustLimit,proto3" json:"dustLimit,omitempty"`
	Delay                uint32   `protobuf:"varint,5,opt,name=delay,proto3" json:"delay,omitempty"`
	PayoutScript         []byte   `protobuf:"bytes,6,opt,name=payoutScript,proto3" json:"payoutScript,omitempty"`
	RevocationPubkey     []byte   `protobuf:"bytes,7,opt,name=revocationPubkey,proto3" json:"revocationPubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelOpen) Reset()         { *m = ChannelOpen{} }
func (m *ChannelOpen) String() string { return proto.CompactTextString(m) }
func (*ChannelOpen) ProtoMessage()    {}
func (*ChannelOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{1}
}

func (m *ChannelOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelOpen.Unmarshal(m, b)
}
func (m *ChannelOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelOpen.Marshal(b, m, deterministic)
}
func (m *ChannelOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelOpen.Merge(m, src)
}
func (m *ChannelOpen) XXX_Size() int {
	return xxx_messageInfo_ChannelOpen.Size(m)
}
func (m *ChannelOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelOpen.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelOpen proto.InternalMessageInfo

func (m *ChannelOpen) GetAddressID() []byte {
	if m != nil {
		return m.AddressID
	}
	return nil
}

func (m *ChannelOpen) GetChannelPubkey() []byte {
	if m != nil {
		return m.ChannelPubkey
	}
	return nil
}

func (m *ChannelOpen) GetFeePerByte() uint32 {
	if m != nil {
		return m.FeePerByte
	}
	return 0
}

func (m *ChannelOpen) GetDustLimit() uint64 {
	if m != nil {
		return m.DustLimit
	}
	return 0
}

func (m *ChannelOpen) GetDelay() uint32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *ChannelOpen) GetPayoutScript() []byte {
	if m != nil {
		return m.PayoutScript
	}
	return nil
}

func (m *ChannelOpen) GetRevocationPubkey() []byte {
	if m != nil {
		return m.RevocationPubkey
	}
	return nil
}

type ChannelAccept struct {
	ChannelPubkey        []byte   `protobuf:"bytes,1,opt,name=channelPubkey,proto3" json:"channelPubkey,omitempty"`
	PayoutScript         []byte   `protobuf:"bytes,2,opt,name=payoutScript,proto3" json:"payoutScript,omitempty"`
	RevocationPubkey     []byte   `protobuf:"bytes,3,opt,name=revocationPubkey,proto3" json:"revocationPubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelAccept) Reset()         { *m = ChannelAccept{} }
func (m *ChannelAccept) String() string { return proto.CompactTextString(m) }
func (*ChannelAccept) ProtoMessage()    {}
func (*ChannelAccept) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{2}
}

func (m *ChannelAccept) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelAccept.Unmarshal(m, b)
}
func (m *ChannelAccept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelAccept.Marshal(b, m, deterministic)
}
func (m *ChannelAccept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelAccept.Merge(m, src)
}
func (m *ChannelAccept) XXX_Size() int {
	return xxx_messageInfo_ChannelAccept.Size(m)
}
func (m *ChannelAccept) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelAccept.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelAccept proto.InternalMessageInfo

func (m *ChannelAccept) GetChannelPubkey() []byte {
	if m != nil {
		return m.ChannelPubkey
	}
	return nil
}

func (m *ChannelAccept) GetPayoutScript() []byte {
	if m != nil {
		return m.PayoutScript
	}
	return nil
}

func (m *ChannelAccept) GetRevocationPubkey() []byte {
	if m != nil {
		return m.RevocationPubkey
	}
	return nil
}

type InitialCommitment struct {
	FundingTxid          string   `protobuf:"bytes,1,opt,name=fundingTxid,proto3" json:"fundingTxid,omitempty"`
	FundingIndex         uint32   `protobuf:"varint,2,opt,name=fundingIndex,proto3" json:"fundingIndex,omitempty"`
	InitialFundingAmount uint64   `protobuf:"varint,3,opt,name=initialFundingAmount,proto3" json:"initialFundingAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialCommitment) Reset()         { *m = InitialCommitment{} }
func (m *InitialCommitment) String() string { return proto.CompactTextString(m) }
func (*InitialCommitment) ProtoMessage()    {}
func (*InitialCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{3}
}

func (m *InitialCommitment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialCommitment.Unmarshal(m, b)
}
func (m *InitialCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialCommitment.Marshal(b, m, deterministic)
}
func (m *InitialCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialCommitment.Merge(m, src)
}
func (m *InitialCommitment) XXX_Size() int {
	return xxx_messageInfo_InitialCommitment.Size(m)
}
func (m *InitialCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_InitialCommitment proto.InternalMessageInfo

func (m *InitialCommitment) GetFundingTxid() string {
	if m != nil {
		return m.FundingTxid
	}
	return ""
}

func (m *InitialCommitment) GetFundingIndex() uint32 {
	if m != nil {
		return m.FundingIndex
	}
	return 0
}

func (m *InitialCommitment) GetInitialFundingAmount() uint64 {
	if m != nil {
		return m.InitialFundingAmount
	}
	return 0
}

type InitialCommitmentSignature struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialCommitmentSignature) Reset()         { *m = InitialCommitmentSignature{} }
func (m *InitialCommitmentSignature) String() string { return proto.CompactTextString(m) }
func (*InitialCommitmentSignature) ProtoMessage()    {}
func (*InitialCommitmentSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{4}
}

func (m *InitialCommitmentSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialCommitmentSignature.Unmarshal(m, b)
}
func (m *InitialCommitmentSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialCommitmentSignature.Marshal(b, m, deterministic)
}
func (m *InitialCommitmentSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialCommitmentSignature.Merge(m, src)
}
func (m *InitialCommitmentSignature) XXX_Size() int {
	return xxx_messageInfo_InitialCommitmentSignature.Size(m)
}
func (m *InitialCommitmentSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialCommitmentSignature.DiscardUnknown(m)
}

var xxx_messageInfo_InitialCommitmentSignature proto.InternalMessageInfo

func (m *InitialCommitmentSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ChannelUpdateProposal struct {
	ChannelID             []byte   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	SerializedTransaction []byte   `protobuf:"bytes,2,opt,name=serializedTransaction,proto3" json:"serializedTransaction,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ChannelUpdateProposal) Reset()         { *m = ChannelUpdateProposal{} }
func (m *ChannelUpdateProposal) String() string { return proto.CompactTextString(m) }
func (*ChannelUpdateProposal) ProtoMessage()    {}
func (*ChannelUpdateProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{5}
}

func (m *ChannelUpdateProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUpdateProposal.Unmarshal(m, b)
}
func (m *ChannelUpdateProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUpdateProposal.Marshal(b, m, deterministic)
}
func (m *ChannelUpdateProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUpdateProposal.Merge(m, src)
}
func (m *ChannelUpdateProposal) XXX_Size() int {
	return xxx_messageInfo_ChannelUpdateProposal.Size(m)
}
func (m *ChannelUpdateProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUpdateProposal.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUpdateProposal proto.InternalMessageInfo

func (m *ChannelUpdateProposal) GetChannelID() []byte {
	if m != nil {
		return m.ChannelID
	}
	return nil
}

func (m *ChannelUpdateProposal) GetSerializedTransaction() []byte {
	if m != nil {
		return m.SerializedTransaction
	}
	return nil
}

type UpdateProposalAccept struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	RevocationPrivKey    []byte   `protobuf:"bytes,3,opt,name=revocationPrivKey,proto3" json:"revocationPrivKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProposalAccept) Reset()         { *m = UpdateProposalAccept{} }
func (m *UpdateProposalAccept) String() string { return proto.CompactTextString(m) }
func (*UpdateProposalAccept) ProtoMessage()    {}
func (*UpdateProposalAccept) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{6}
}

func (m *UpdateProposalAccept) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProposalAccept.Unmarshal(m, b)
}
func (m *UpdateProposalAccept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProposalAccept.Marshal(b, m, deterministic)
}
func (m *UpdateProposalAccept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProposalAccept.Merge(m, src)
}
func (m *UpdateProposalAccept) XXX_Size() int {
	return xxx_messageInfo_UpdateProposalAccept.Size(m)
}
func (m *UpdateProposalAccept) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProposalAccept.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProposalAccept proto.InternalMessageInfo

func (m *UpdateProposalAccept) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *UpdateProposalAccept) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *UpdateProposalAccept) GetRevocationPrivKey() []byte {
	if m != nil {
		return m.RevocationPrivKey
	}
	return nil
}

type FinalizeUpdate struct {
	RevocationPrivKey    []byte   `protobuf:"bytes,1,opt,name=revocationPrivKey,proto3" json:"revocationPrivKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizeUpdate) Reset()         { *m = FinalizeUpdate{} }
func (m *FinalizeUpdate) String() string { return proto.CompactTextString(m) }
func (*FinalizeUpdate) ProtoMessage()    {}
func (*FinalizeUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{7}
}

func (m *FinalizeUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeUpdate.Unmarshal(m, b)
}
func (m *FinalizeUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeUpdate.Marshal(b, m, deterministic)
}
func (m *FinalizeUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeUpdate.Merge(m, src)
}
func (m *FinalizeUpdate) XXX_Size() int {
	return xxx_messageInfo_FinalizeUpdate.Size(m)
}
func (m *FinalizeUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeUpdate proto.InternalMessageInfo

func (m *FinalizeUpdate) GetRevocationPrivKey() []byte {
	if m != nil {
		return m.RevocationPrivKey
	}
	return nil
}

type Shutdown struct {
	ChannelID            []byte   `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shutdown) Reset()         { *m = Shutdown{} }
func (m *Shutdown) String() string { return proto.CompactTextString(m) }
func (*Shutdown) ProtoMessage()    {}
func (*Shutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{8}
}

func (m *Shutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shutdown.Unmarshal(m, b)
}
func (m *Shutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shutdown.Marshal(b, m, deterministic)
}
func (m *Shutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shutdown.Merge(m, src)
}
func (m *Shutdown) XXX_Size() int {
	return xxx_messageInfo_Shutdown.Size(m)
}
func (m *Shutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_Shutdown.DiscardUnknown(m)
}

var xxx_messageInfo_Shutdown proto.InternalMessageInfo

func (m *Shutdown) GetChannelID() []byte {
	if m != nil {
		return m.ChannelID
	}
	return nil
}

func (m *Shutdown) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaa1143a269126c4, []int{9}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*ChannelOpen)(nil), "ChannelOpen")
	proto.RegisterType((*ChannelAccept)(nil), "ChannelAccept")
	proto.RegisterType((*InitialCommitment)(nil), "InitialCommitment")
	proto.RegisterType((*InitialCommitmentSignature)(nil), "InitialCommitmentSignature")
	proto.RegisterType((*ChannelUpdateProposal)(nil), "ChannelUpdateProposal")
	proto.RegisterType((*UpdateProposalAccept)(nil), "UpdateProposalAccept")
	proto.RegisterType((*FinalizeUpdate)(nil), "FinalizeUpdate")
	proto.RegisterType((*Shutdown)(nil), "Shutdown")
	proto.RegisterType((*Error)(nil), "Error")
}

func init() { proto.RegisterFile("paymentchannels.proto", fileDescriptor_eaa1143a269126c4) }

var fileDescriptor_eaa1143a269126c4 = []byte{
	// 674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x6f, 0x12, 0x41,
	0x14, 0xc7, 0x5d, 0x0a, 0x85, 0x3e, 0xa0, 0x6e, 0x47, 0xaa, 0x2b, 0x36, 0x06, 0x37, 0x1e, 0x88,
	0x31, 0x34, 0xa9, 0xc6, 0x83, 0x07, 0x93, 0x2d, 0x5d, 0xec, 0x46, 0x0a, 0x9b, 0x61, 0x89, 0x49,
	0x2f, 0x64, 0x60, 0xa7, 0x74, 0x52, 0x98, 0xdd, 0xec, 0xce, 0xd6, 0xae, 0x07, 0x6f, 0x1e, 0xfd,
	0x9f, 0xfc, 0x03, 0xfc, 0x77, 0xbc, 0x9b, 0xfd, 0x45, 0xa1, 0x50, 0xf5, 0xc4, 0xbe, 0xcf, 0x9b,
	0x37, 0xef, 0x3b, 0xdf, 0x37, 0x0c, 0xec, 0xbb, 0x24, 0x9c, 0x53, 0x2e, 0x26, 0x97, 0x84, 0x73,
	0x3a, 0xf3, 0x5b, 0xae, 0xe7, 0x08, 0xa7, 0xfe, 0x74, 0xea, 0x38, 0xd3, 0x19, 0x3d, 0x8c, 0xa3,
	0x71, 0x70, 0x71, 0x48, 0x78, 0x98, 0xa4, 0xd4, 0x9f, 0x39, 0x28, 0x9e, 0x51, 0xdf, 0x27, 0x53,
	0x8a, 0xde, 0x41, 0x79, 0x9e, 0x7c, 0x5a, 0xa1, 0x4b, 0x15, 0xa9, 0x21, 0x35, 0x77, 0x8f, 0x6a,
	0xad, 0x34, 0x9d, 0xfd, 0x46, 0x39, 0xbc, 0xbc, 0x10, 0xb5, 0xa0, 0xe8, 0x92, 0x70, 0xe6, 0x10,
	0x5b, 0xc9, 0x35, 0xa4, 0x66, 0xf9, 0xa8, 0xd6, 0x4a, 0x1a, 0xb6, 0xb2, 0x86, 0x2d, 0x8d, 0x87,
	0x38, 0x5b, 0xa4, 0xfe, 0x92, 0xa0, 0xbc, 0xb4, 0x19, 0x92, 0xa1, 0xd2, 0x3e, 0xd5, 0x7a, 0x3d,
	0xbd, 0x3b, 0xea, 0x9b, 0x7a, 0x4f, 0x7e, 0x80, 0x10, 0xec, 0x66, 0x44, 0x6b, 0xb7, 0x75, 0xd3,
	0x92, 0xa5, 0x88, 0x19, 0x3d, 0xc3, 0x32, 0xb4, 0xee, 0xa8, 0xdd, 0x3f, 0x3b, 0x33, 0x2c, 0x39,
	0x87, 0x0e, 0x40, 0x59, 0x65, 0xa3, 0x81, 0xf1, 0xb1, 0xa7, 0x59, 0x43, 0xac, 0xcb, 0x5b, 0xe8,
	0x19, 0x3c, 0xc9, 0x76, 0x19, 0x9a, 0x27, 0x9a, 0xa5, 0x8f, 0x4c, 0xdc, 0x37, 0xfb, 0x03, 0xad,
	0x2b, 0xe7, 0x51, 0x1d, 0x1e, 0xdf, 0x81, 0x59, 0xab, 0x02, 0x7a, 0x04, 0x0f, 0x3b, 0x46, 0x4f,
	0xeb, 0x1a, 0xe7, 0x7a, 0x5a, 0x29, 0x6f, 0xa3, 0x0a, 0x94, 0x06, 0xa7, 0x43, 0xeb, 0xa4, 0xff,
	0xb9, 0x27, 0x17, 0xd1, 0x0e, 0x14, 0x74, 0x8c, 0xfb, 0x58, 0x2e, 0xa9, 0xbf, 0x25, 0x28, 0xb7,
	0x13, 0xc3, 0xfb, 0x2e, 0xe5, 0xe8, 0x00, 0x76, 0x88, 0x6d, 0x7b, 0xd4, 0xf7, 0x8d, 0x93, 0xd8,
	0xc4, 0x0a, 0xbe, 0x05, 0xe8, 0x25, 0x54, 0xd3, 0xe9, 0x98, 0xc1, 0xf8, 0x8a, 0x86, 0xb1, 0x65,
	0x15, 0xbc, 0x0a, 0xd1, 0x73, 0x80, 0x0b, 0x4a, 0x4d, 0xea, 0x1d, 0x87, 0x82, 0x2a, 0x5b, 0x0d,
	0xa9, 0x59, 0xc5, 0x4b, 0x24, 0xea, 0x61, 0x07, 0xbe, 0xe8, 0xb2, 0x39, 0x13, 0x4a, 0xbe, 0x21,
	0x35, 0xf3, 0xf8, 0x16, 0xa0, 0x1a, 0x14, 0x6c, 0x3a, 0x23, 0xa1, 0x52, 0x88, 0x0b, 0x93, 0x00,
	0xa9, 0x50, 0x71, 0x49, 0xe8, 0x04, 0x62, 0x30, 0xf1, 0x98, 0x2b, 0x94, 0xed, 0xb8, 0xf1, 0x0a,
	0x43, 0xaf, 0x40, 0xf6, 0xe8, 0xb5, 0x33, 0x21, 0x82, 0x39, 0x3c, 0x15, 0x58, 0x8c, 0xd7, 0xad,
	0x71, 0xf5, 0xbb, 0x04, 0xd5, 0xf4, 0xdc, 0xda, 0x64, 0x42, 0x5d, 0xb1, 0x7e, 0x36, 0x69, 0xd3,
	0xd9, 0xee, 0xea, 0xc8, 0xfd, 0xa7, 0x8e, 0xad, 0x7b, 0x74, 0xfc, 0x90, 0x60, 0xcf, 0xe0, 0x4c,
	0x30, 0x32, 0x6b, 0x3b, 0xf3, 0x39, 0x13, 0xd1, 0x3f, 0x00, 0x35, 0xa0, 0x7c, 0x11, 0x70, 0x9b,
	0xf1, 0xa9, 0x75, 0xc3, 0xec, 0x58, 0xc9, 0x0e, 0x5e, 0x46, 0x91, 0x8e, 0x34, 0x34, 0xb8, 0x4d,
	0x6f, 0x62, 0x1d, 0x55, 0xbc, 0xc2, 0xd0, 0x11, 0xd4, 0x58, 0xb2, 0x75, 0x27, 0xc1, 0xda, 0xdc,
	0x09, 0xb8, 0x88, 0xb5, 0xe4, 0xf1, 0xc6, 0x9c, 0xfa, 0x1e, 0xea, 0x6b, 0x72, 0x06, 0x6c, 0xca,
	0x89, 0x08, 0xbc, 0x78, 0x72, 0x7e, 0x16, 0x64, 0xb7, 0x63, 0x01, 0xd4, 0x2b, 0xd8, 0x4f, 0x2d,
	0x1d, 0xba, 0x36, 0x11, 0xd4, 0xf4, 0x1c, 0xd7, 0xf1, 0xc9, 0x2c, 0x2a, 0x4b, 0x5d, 0xbc, 0xbd,
	0x54, 0x0b, 0x80, 0xde, 0xc2, 0xbe, 0x4f, 0x3d, 0x46, 0x66, 0xec, 0x2b, 0xb5, 0x2d, 0x8f, 0x70,
	0x9f, 0x4c, 0x22, 0x87, 0x52, 0x6f, 0x37, 0x27, 0xd5, 0x6f, 0x50, 0x5b, 0xed, 0x92, 0x8e, 0xb1,
	0x0e, 0x25, 0x12, 0x7f, 0xd1, 0xc4, 0xb7, 0x12, 0x5e, 0xc4, 0xab, 0xf2, 0x73, 0x77, 0xe4, 0xa3,
	0xd7, 0xb0, 0xb7, 0x34, 0x1e, 0x8f, 0x5d, 0x7f, 0x5a, 0xcc, 0x6d, 0x3d, 0xa1, 0x7e, 0x80, 0xdd,
	0x0e, 0xe3, 0xb1, 0xae, 0x44, 0xc7, 0xe6, 0x7a, 0xe9, 0xbe, 0xfa, 0x0e, 0x94, 0x06, 0x97, 0x81,
	0xb0, 0x9d, 0x2f, 0xfc, 0x1f, 0xfe, 0xfc, 0x55, 0xb5, 0xfa, 0x02, 0x0a, 0xba, 0xe7, 0x39, 0x1e,
	0x52, 0xa0, 0x98, 0xbe, 0x6b, 0xe9, 0x7d, 0xc9, 0xc2, 0xe3, 0xfc, 0x79, 0xce, 0x1d, 0x8f, 0xb7,
	0xe3, 0xf7, 0xec, 0xcd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xef, 0xa1, 0xac, 0x67, 0x05,
	0x00, 0x00,
}
